// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatchManagement.Persistence;

#nullable disable

namespace PatchManagement.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820144646_ThirdPartyApplicationVocabulary")]
    partial class ThirdPartyApplicationVocabulary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PatchManagement.Persistence.Entities.Advisory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("CvssBaseScore")
                        .HasColumnType("double precision")
                        .HasColumnName("cvss_base_score");

                    b.Property<string>("CvssSource")
                        .HasColumnType("text")
                        .HasColumnName("cvss_source");

                    b.Property<string>("CvssVector")
                        .HasColumnType("text")
                        .HasColumnName("cvss_vector");

                    b.Property<string>("CvssVersion")
                        .HasColumnType("text")
                        .HasColumnName("cvss_version");

                    b.Property<double?>("EpssPercentile")
                        .HasColumnType("double precision")
                        .HasColumnName("epss_percentile");

                    b.Property<double?>("EpssScore")
                        .HasColumnType("double precision")
                        .HasColumnName("epss_score");

                    b.Property<DateTimeOffset?>("EpssScoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("epss_scored_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateOnly?>("KevDateAdded")
                        .HasColumnType("date")
                        .HasColumnName("kev_date_added");

                    b.Property<DateOnly?>("KevDueDate")
                        .HasColumnType("date")
                        .HasColumnName("kev_due_date");

                    b.Property<bool?>("KevKnownRansomwareUse")
                        .HasColumnType("boolean")
                        .HasColumnName("kev_known_ransomware_use");

                    b.Property<bool?>("KevListed")
                        .HasColumnType("boolean")
                        .HasColumnName("kev_listed");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("provenance");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RawRef")
                        .HasColumnType("text")
                        .HasColumnName("raw_ref");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_metadata");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_advisories");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_advisories_source_external_id");

                    b.ToTable("advisories", null, t =>
                        {
                            t.HasCheckConstraint("ck_advisories_cvss_base_score", "cvss_base_score IS NULL OR (cvss_base_score >= 0 AND cvss_base_score <= 10)");

                            t.HasCheckConstraint("ck_advisories_cvss_source", "cvss_source IS NULL OR cvss_source IN ('nvd', 'kev', 'epss', 'usn', 'rhsa', 'msrc', 'wsusscn2', 'dsa', 'vendor')");

                            t.HasCheckConstraint("ck_advisories_cvss_version", "cvss_version IS NULL OR cvss_version IN ('2.0', '3.0', '3.1', '4.0')");

                            t.HasCheckConstraint("ck_advisories_epss_percentile", "epss_percentile IS NULL OR (epss_percentile >= 0 AND epss_percentile <= 1)");

                            t.HasCheckConstraint("ck_advisories_epss_score", "epss_score IS NULL OR (epss_score >= 0 AND epss_score <= 1)");

                            t.HasCheckConstraint("ck_advisories_provenance_non_empty", "jsonb_typeof(provenance) = 'array' AND jsonb_array_length(provenance) >= 1");

                            t.HasCheckConstraint("ck_advisories_severity", "severity IN ('none', 'low', 'medium', 'high', 'critical', 'unknown')");

                            t.HasCheckConstraint("ck_advisories_source", "source IN ('nvd', 'usn', 'rhsa', 'msrc', 'dsa', 'vendor')");
                        });
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.AdvisoryAffects", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdvisoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("advisory_id");

                    b.Property<bool>("Backported")
                        .HasColumnType("boolean")
                        .HasColumnName("backported");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Ecosystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ecosystem");

                    b.Property<string>("FixedVersion")
                        .HasColumnType("text")
                        .HasColumnName("fixed_version");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_name");

                    b.Property<string>("Platform")
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.HasKey("Id")
                        .HasName("pk_advisory_affects");

                    b.HasIndex("PackageName", "Ecosystem")
                        .HasDatabaseName("ix_advisory_affects_package_name_ecosystem");

                    b.HasIndex("AdvisoryId", "PackageName", "Ecosystem", "Platform")
                        .IsUnique()
                        .HasDatabaseName("ix_advisory_affects_advisory_id_package_name_ecosystem_platform");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("AdvisoryId", "PackageName", "Ecosystem", "Platform"), false);

                    b.ToTable("advisory_affects", null, t =>
                        {
                            t.HasCheckConstraint("ck_advisory_affects_ecosystem", "ecosystem IN ('deb', 'rpm', 'windows', 'app')");
                        });
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<bool>("Managed")
                        .HasColumnType("boolean")
                        .HasColumnName("managed");

                    b.Property<string>("OsFamily")
                        .HasColumnType("text")
                        .HasColumnName("os_family");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text")
                        .HasColumnName("os_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_assets_tenant_id_id");

                    b.HasIndex("TenantId", "Hostname")
                        .HasDatabaseName("ix_assets_tenant_id_hostname");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.AssetPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Arch")
                        .HasColumnType("text")
                        .HasColumnName("arch");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Epoch")
                        .HasColumnType("integer")
                        .HasColumnName("epoch");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_asset_packages");

                    b.HasIndex("TenantId", "AssetId")
                        .HasDatabaseName("ix_asset_packages_tenant_id_asset_id");

                    b.ToTable("asset_packages", (string)null);
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("TenantId", "At")
                        .HasDatabaseName("ix_audit_log_tenant_id_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.ContentSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cursor")
                        .HasColumnType("text")
                        .HasColumnName("cursor");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instance");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("LastStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_status");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_content_sources");

                    b.HasIndex("Kind", "Instance")
                        .IsUnique()
                        .HasDatabaseName("ix_content_sources_kind_instance");

                    b.ToTable("content_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_content_sources_kind", "kind IN ('nvd', 'kev', 'epss', 'usn', 'rhsa', 'msrc', 'wsusscn2', 'dsa', 'vendor')");

                            t.HasCheckConstraint("ck_content_sources_last_status", "last_status IN ('ok', 'failed', 'never-run')");
                        });
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DataKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_key_id");

                    b.Property<byte[]>("Envelope")
                        .HasColumnType("bytea")
                        .HasColumnName("envelope");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TargetScope")
                        .HasColumnType("text")
                        .HasColumnName("target_scope");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("TenantId", "DataKeyId")
                        .HasDatabaseName("ix_credentials_tenant_id_data_key_id");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.DataKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyId")
                        .HasColumnType("text")
                        .HasColumnName("key_id");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<byte[]>("WrappedDek")
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_dek");

                    b.HasKey("Id")
                        .HasName("pk_data_keys");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_data_keys_tenant_id_id");

                    b.ToTable("data_keys", (string)null);
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdvisoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("advisory_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid?>("PatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("patch_id");

                    b.Property<bool>("Reversible")
                        .HasColumnType("boolean")
                        .HasColumnName("reversible");

                    b.Property<string>("RiskExplanation")
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_explanation");

                    b.Property<double?>("RiskScore")
                        .HasColumnType("double precision")
                        .HasColumnName("risk_score");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_findings");

                    b.HasIndex("AdvisoryId")
                        .HasDatabaseName("ix_findings_advisory_id");

                    b.HasIndex("PatchId")
                        .HasDatabaseName("ix_findings_patch_id");

                    b.HasIndex("TenantId", "AssetId")
                        .HasDatabaseName("ix_findings_tenant_id_asset_id");

                    b.HasIndex("TenantId", "State")
                        .HasDatabaseName("ix_findings_tenant_id_state");

                    b.ToTable("findings", (string)null);
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalAuthRef")
                        .HasColumnType("text")
                        .HasColumnName("external_auth_ref");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_operators");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_operators_tenant_id_email");

                    b.ToTable("operators", (string)null);
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.Patch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("provenance");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<bool>("RequiresReboot")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_reboot");

                    b.Property<bool>("Reversible")
                        .HasColumnType("boolean")
                        .HasColumnName("reversible");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_metadata");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendor_id");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_patches");

                    b.HasIndex("Source", "VendorId")
                        .IsUnique()
                        .HasDatabaseName("ix_patches_source_vendor_id");

                    b.ToTable("patches", null, t =>
                        {
                            t.HasCheckConstraint("ck_patches_provenance_non_empty", "jsonb_typeof(provenance) = 'array' AND jsonb_array_length(provenance) >= 1");

                            t.HasCheckConstraint("ck_patches_source", "source IN ('usn', 'rhsa', 'msrc', 'wsusscn2', 'dsa', 'vendor')");
                        });
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.PatchSupersedence", b =>
                {
                    b.Property<Guid>("PatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("patch_id");

                    b.Property<Guid>("SupersededByPatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_patch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("PatchId", "SupersededByPatchId")
                        .HasName("pk_patch_supersedence");

                    b.HasIndex("SupersededByPatchId")
                        .HasDatabaseName("ix_patch_supersedence_superseded_by_patch_id");

                    b.ToTable("patch_supersedence", null, t =>
                        {
                            t.HasCheckConstraint("ck_patch_supersedence_no_self_loop", "patch_id <> superseded_by_patch_id");
                        });
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.AdvisoryAffects", b =>
                {
                    b.HasOne("PatchManagement.Persistence.Entities.Advisory", "Advisory")
                        .WithMany()
                        .HasForeignKey("AdvisoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_advisory_affects_advisories_advisory_id");

                    b.Navigation("Advisory");
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.Asset", b =>
                {
                    b.HasOne("PatchManagement.Persistence.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assets_tenants_tenant_id");
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.AssetPackage", b =>
                {
                    b.HasOne("PatchManagement.Persistence.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_packages_tenants_tenant_id");

                    b.HasOne("PatchManagement.Persistence.Entities.Asset", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_packages_assets_tenant_id_asset_id");
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("PatchManagement.Persistence.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_tenants_tenant_id");
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.Credential", b =>
                {
                    b.HasOne("PatchManagement.Persistence.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credentials_tenants_tenant_id");

                    b.HasOne("PatchManagement.Persistence.Entities.DataKey", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DataKeyId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_credentials_data_keys_tenant_id_data_key_id");
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.DataKey", b =>
                {
                    b.HasOne("PatchManagement.Persistence.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_data_keys_tenants_tenant_id");
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.Finding", b =>
                {
                    b.HasOne("PatchManagement.Persistence.Entities.Advisory", null)
                        .WithMany()
                        .HasForeignKey("AdvisoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_findings_advisories_advisory_id");

                    b.HasOne("PatchManagement.Persistence.Entities.Patch", null)
                        .WithMany()
                        .HasForeignKey("PatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_findings_patches_patch_id");

                    b.HasOne("PatchManagement.Persistence.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_findings_tenants_tenant_id");

                    b.HasOne("PatchManagement.Persistence.Entities.Asset", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_findings_assets_tenant_id_asset_id");
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.Operator", b =>
                {
                    b.HasOne("PatchManagement.Persistence.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operators_tenants_tenant_id");
                });

            modelBuilder.Entity("PatchManagement.Persistence.Entities.PatchSupersedence", b =>
                {
                    b.HasOne("PatchManagement.Persistence.Entities.Patch", "Patch")
                        .WithMany()
                        .HasForeignKey("PatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patch_supersedence_patches_patch_id");

                    b.HasOne("PatchManagement.Persistence.Entities.Patch", "SupersededByPatch")
                        .WithMany()
                        .HasForeignKey("SupersededByPatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patch_supersedence_patches_superseded_by_patch_id");

                    b.Navigation("Patch");

                    b.Navigation("SupersededByPatch");
                });
#pragma warning restore 612, 618
        }
    }
}
