namespace PatchManagement.TestSupport;

/// <summary>
/// Locates the checkout from a test's output directory. Convention scans must anchor on the
/// repository, never on the working directory, which differs between the IDE, the CLI and a
/// worktree. Mirrors the walk-up used by the vault's convention tests.
/// </summary>
public static class RepoPaths
{
    /// <summary>
    /// Walks up from the running assembly's directory until it finds the solution file.
    /// Throws with the starting point named, because "file not found" is useless here —
    /// the interesting fact is always <em>where it started looking</em>.
    /// </summary>
    public static DirectoryInfo RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "PatchManagement.sln")))
            dir = dir.Parent;

        return dir ?? throw new InvalidOperationException(
            $"Could not locate PatchManagement.sln walking up from '{AppContext.BaseDirectory}'.");
    }

    /// <summary>A path under the repository root, e.g. <c>Source("src", "Modules", "Connectors")</c>.</summary>
    public static string Source(params string[] segments) =>
        Path.Combine(new[] { RepoRoot().FullName }.Concat(segments).ToArray());

    /// <summary>
    /// The lab fleet's ed25519 private key. Gitignored, generated by <c>scripts/lab-keygen.ps1</c>,
    /// and propagated into worktrees by <c>.worktreeinclude</c> — so its absence in a worktree means
    /// the worktree was created outside that tooling, not that the key was never generated.
    /// </summary>
    public static string LabPrivateKey() => Source("lab", "keys", "lab_ed25519");
}
